#!/bin/bash

gnuplot << EOF
set key left top
set term eps enhanced color solid lw 2 size 10in,7in font  'Helvetica,14'
set output '$1_curveY_$2vs$3.eps'
set title "$1-curveY-$vs$32"
set ylabel "amplitude"
set xlabel "y"
set xrange [0:$4]
set palette gray
plot "$1.dat" using $2 with linespoints pt 3 ps 0.1 lc rgb "#0000FF","$1.dat" using $3 with linespoints pt 3 ps 0.1 lc rgb "#EE1D1D" 
EOF
epstopdf $1_curveY_$2vs$3.eps
rm $1_curveY_$2vs$3.eps
okular $1_curveY_$2vs$3.pdf &
