#!/bin/bash

gnuplot << EOF
unset key
set term eps enhanced color solid  lw 2 font  'Helvetica,12'
set size ratio -1
set output '$1.eps'
set title "$1"
set contour base
set cntrparam levels 100
set xrange[0:$2]
set yrange[0:$3]
set xlabel "X"
set ylabel "Y"
unset surface
set view map
#set palette gray
splot "$1.dat" matrix with lines palette gray
EOF
epstopdf $1.eps
rm $1.eps
okular $1.pdf
