#!/bin/bash
awk '{
       for (f = 1; f <= NF; f++) { a[NR, f] = $f } 
     }
     NF > nf { nf = NF }
     END {
       for (f = 1; f <= nf; f++) {
           for (r = 1; r <= NR; r++) {
               printf a[r, f] (r==NR ? RS : FS)
           }
       }
    }' $1.dat>>x.dat


gnuplot << EOF
unset key
set term eps enhanced color solid  lw 2 font  'Helvetica,6'
set output '$1_trans.eps'
set title "$1-trans"
set ylabel "amplitude"
set xlabel "X"
set xrange [0:$2]
set palette gray
plot "x.dat" using $3 with linespoints pt 3 ps 0.1 lc rgb "#000000"
EOF
epstopdf $1_trans.eps
rm $1_trans.eps
rm x.dat
okular $1_trans.pdf
